### ISSUE TITLE
Issue with build (.git related)

### ISSUE THREAD

**Issue by alechp** [julianburr/sketch-plugin-boilerplate#3]
The build doesn't complete properly the first time because the frameworks directory is missing.

Perhaps you could add an empty hidden file (e.g. `.foo`) so that frameworks will be uploaded with the directory?

Quick-fix for anyone cloning is just to create `frameworks` directory locally (ie. in ~sketch-plugin-boilerplate/src/).

**Comment by julianburr** [comment]
Good catch 😊  Yeah, I got rid of the framework dependency for webviews, but the folder was still around for me so I didn't notice, thanks for reporting it :blush:

I changed the framework step in the build process to be conditional (it will only do sth if there actually are frameworks to copy) + added a `.gitkeep` file in the frameworks folder, this should fix the issue.
